# -*- coding: utf-8 -*-
"""Coachbot 1_0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1t69Sh2TOSg0vcyGEycFi131eWD1dLXz7
"""

import json
from datetime import datetime
import random
import re
import sys
import requests
class Chatbot:
  def __init__(self, name="ChatBot", claves_url=""):
    self.repetir=0
    self.name=name.title()
    self.tiempo_sesion=[]
    self.tiempo_tema_obj=[]
    self.tiempo_import=[]
    self.tiempo_indicador=[]
    self.tiempo_explorar=[]
    self.tiempo_verif=[]
    self.tiempo_aprend=[]
    self.tema=""
    self.objetivos=[]
    self.conversacion="Registro de la conversación\n\n"
    self.solucion=""

    self.Bot(1,"Hola, mi nombre es", self.name)
    self.Bot(0,"¿Cuál es tu nombre?", ":")
    self.usuario=self.mensaje_usuario().title()

    self.claves=self.Get_Diccionario_Claves(claves_url)

    self.bienvenida()
    
    while True:
      respuesta=self.mensaje_usuario()
      if respuesta.title() in self.claves["Afirmacion"]:
        self.Presentacion()
        break
      elif respuesta.title() in self.claves["Negacion"]:
        self.Despedida()
        break
      else:
        self.repetir+=1
        if self.repetir>3:
          self.No_avanza()
          break
        else:
          self.Respuesta_default()
    self.repetir=0


    # Actividades GROW
    self.titulo_grow=["Conversación", "Tema y Objs ", "Importancia ", "Indicador(s)",
                 "Explorar\t", "Verifica\t", "Aprendizaje "]
    self.Tema_obj()
    self.Importancia()
    self.Indicador()
    self.Explorar()
    self.Verificar()
    self.Aprendizaje()
    self.Despedida()

  ##############################################################################
  def Bot(self, bot=True,*mensaje):
    if bot==True:
      respuesta=self.name,":", *mensaje
    else:
      respuesta="\t", *mensaje
    respuesta=" ".join(respuesta)
    self.conversacion+=respuesta
    self.conversacion+="\n"
    print(respuesta)
  
  ##############################################################################
  def Presentacion(self):
    self.Bot(1, self.respuesta("Agradecimiento"), self.usuario,
          ", La sesión\n\t estará compuesta de 5 pasos",
          "\n\t * Primero hay que plantear el tema y objetivo de la sesión.",
          "\n\t * Segundo es la importancia que tiene la sesión para ti.",
          "\n\t * Tercero es la definición del indicador de que la sesión es exitosa para ti."
          "\n\t * Cuarto será explorar el tema y los elementos que la componen.",
          "\n\t * Quinto es la verificación de las ideas propuestas.",
          "\n\t * Por último y ya para terminar, revisar el aprendizaje de la sesión.",
          "\n\t Comencemos    :-)")

    self.marco("inicio")
  
  ##############################################################################
  def Get_Diccionario_Claves(self, ruta=""):
    resp = requests.get(ruta)
    dictionary = json.loads(resp.text)
    return dictionary

  ##############################################################################
  def mensaje_usuario(self):
    mensaje=input("Usuario : ")
    self.conversacion+="Usuario : "
    self.conversacion+=mensaje
    self.conversacion+="\n"
    print()
    while True:
      if mensaje[-1]=="?" or mensaje=="":
        self.Respuesta_default()
        mensaje=self.mensaje=mensaje_usuario()
      else:
        break
    return mensaje

  ##############################################################################
  def respuesta(self, tema):
    return random.choice(self.claves[tema])

  ##############################################################################
  def bienvenida(self):
    self.Bot(1, self.respuesta("Saludo"),self.usuario,
          ", Soy un Chatbot\n\t diseñado para Coaching estudiantil.",
          "\n\t Mi objetivo es poder ayudarte.\n\t ¿Te parece si comenzamos?")

  ##############################################################################
  def marco(self, concepto):
    if concepto=="inicio":
      self.tiempo_sesion.append(str(datetime.now())[:-7])
    elif concepto=="termino":
      self.tiempo_sesion.append(str(datetime.now())[:-7])
    texto="\n\t Hora de", concepto, ":", str(datetime.now())[:-7]
    print("-"*70)
    print(" ".join(texto))
    print("-"*70)
    self.conversacion+="-"*70
    self.conversacion+=" ".join(texto)
    self.conversacion+="-"*70
  
  
  ##############################################################################
  def Respuesta_default(self):
      self.Bot(1, self.respuesta("Default"))

  ##############################################################################
  def Tema_obj(self):
    self.Bot(1, self.respuesta("Agradecimiento"), self.usuario, ",",
          "\n\t ", self.respuesta("Tema"))
    self.tiempo_tema_obj.append(str(datetime.now())[:-7])

    self.tema=self.Cambiar_pronombres(self.mensaje_usuario())

    if self.tema[-1]=="s": 
      self.Bot(1, self.respuesta("Comprensiva"),",", self.tema, "te preocupan.")
    else:
      self.Bot(1, self.respuesta("Comprensiva"),",", self.tema, "te preocupa.")

    self.Bot(1, "Ahora bien, que objetivo(s) te gustaría", self.respuesta("Verbo"), "con respecto a", self.tema)
    self.Bot(0, "Recuerda utilizar un verbo en infinitivo para que yo pueda identificar el objetivo:")
    while len(self.objetivos)<=3:
      if len(self.objetivos)!=0:
        self.Bot(1, self.respuesta("Afirmacion"),"¿Te gustaría agregar otro objetivo?")
      respuesta_usuario=self.Cambiar_pronombres(self.mensaje_usuario())

      if self.Negativa(respuesta_usuario):
        break
      objs=len(self.objetivos)
      for palabra in respuesta_usuario.split(" "):
        if palabra[-2:] in ["ar", "er", "ir"]:
          i=respuesta_usuario.index(palabra)
          self.objetivos.append(respuesta_usuario[i:])
          break
      if objs==len(self.objetivos):
        self.Bot(1, "Me parece que no usaste un objetivo en donde el verbo estuviera en infinitivo.")
        self.repetir+=1
        if self.repetir>3:
          self.No_avanza()
          continue
      else:
        self.repetir=0
      
      if len(self.objetivos)==3:
        self.Bot(1, "Considero que 3 objetivos son más que suficientes.")
        self.Bot(0, "Lo demás pordemos manejarlo en una próxima sesión.")
        break
      if len(respuesta_usuario)<=2:
        self.Bot(1 , self.respuesta("Comprensiva"),self.respuesta("Indagar"))
    self.Bot(1, "Para esta sesión se abordará el tema de", self.tema.lower())
    if len(self.objetivos)==0:
      self.No_avanza()

    elif len(self.objetivos)==1:
      self.Bot(0, "Con el siguiente objetivo en mente:")

    else:
      self.Bot(0, "Con los siguientes objetivos en mente:")

    for obj in self.objetivos:
      self.Bot(0, "\t *",obj)
    self.Bot(0)
    self.tiempo_tema_obj.append(str(datetime.now())[:-7])
    
  ##############################################################################
  def Importancia(self):
    self.tiempo_import.append(str(datetime.now())[:-7])
    if len(self.objetivos)==1:
      self.Bot(1, "Ya que se definió el tema de nuestra charla,", self.tema) 
      self.Bot(0, "y el objetivo de nuestra sesión:,", self.objetivos[0], ";")
    else:
      self.Bot(1, "Ya se ha definido el tema de nuestra charla de hoy,", self.tema,) 
      self.Bot(0 ,"Así mismo, tenemos {} objetivos que debemos revisar.".format(len(self.objetivos)))
    self.Bot(0, self.respuesta("Cambio"), self.usuario, ",")
    for n in range(len(self.objetivos)):
      self.Bot(1, self.respuesta("Afirmacion"), ",", self.respuesta("Opciones"), self.objetivos[n], ",")
      self.Bot(0, self.respuesta("Rebotar0").format(self.objetivos[n]))
      respuesta=self.Cambiar_pronombres(self.mensaje_usuario())
      for i in range(1):
        self.Bot(1, self.respuesta("Comprensiva"))
        self.Bot(0, self.respuesta("Rebotar"))
        respuesta=self.Cambiar_pronombres(self.mensaje_usuario())
        if self.Negativa(respuesta):
          break
    
    self.tiempo_import.append(str(datetime.now())[:-7])

  ##############################################################################
  def Indicador(self):
    self.tiempo_indicador.append(str(datetime.now())[:-7])
    self.Bot(1, "Ya que charlamos sobre la importancia que tiene {0} para ti".format(self.tema))
    self.Bot(0, "junto con su(s) objetivo(s)...")
    self.Bot(0, self.respuesta("Cambio"), self.usuario, ",")
    self.Bot(0, self.respuesta("Indicador"))
    respuesta=self.Cambiar_pronombres(self.mensaje_usuario())
    self.tiempo_indicador.append(str(datetime.now())[:-7])

  ##############################################################################
  def Explorar(self):
    self.tiempo_explorar.append(str(datetime.now())[:-7])
    self.Bot(1, self.respuesta("Afirmacion"), self.usuario, ",")
    self.Bot(0, "Ahora exploremos los posibles resultados de poder", self.respuesta("Verbo"))
    self.Bot(0, "de forma exitosa ", self.tema, ".")
    explorar=["Explorar1","Explorar2","Explorar3"]
    for exp in explorar:
      self.Bot(1, self.respuesta(exp))
      respuesta=self.Cambiar_pronombres(self.mensaje_usuario())
      if exp=="Explorar2" and self.solucion=="":
        self.solucion=respuesta
      for i in range(2):
        self.Bot(1, self.respuesta("Comprensiva"))
        self.Bot(0, self.respuesta("Rebotar"))
        respuesta=self.Cambiar_pronombres(self.mensaje_usuario())
        if self.Negativa(respuesta):
          break
    
    self.tiempo_explorar.append(str(datetime.now())[:-7])

  ##############################################################################
  def Verificar(self):
    self.tiempo_verif.append(str(datetime.now())[:-7])
    self.Bot(1, self.respuesta("Afirmacion"), self.usuario, ",")
    self.Bot(0, "Ahora exploremos los posibles resultados de poder", self.respuesta("Verbo"))
    self.Bot(0, "de forma exitosa ", self.tema, ".")
    verificar=["Verificar1","Verificar2"]
    for verif in verificar:
      self.Bot(1, self.respuesta(verif).format(self.solucion))
      respuesta=self.Cambiar_pronombres(self.mensaje_usuario())
    self.tiempo_verif.append(str(datetime.now())[:-7])

  ##############################################################################
  def Aprendizaje(self):
    self.tiempo_aprend.append(str(datetime.now())[:-7])
    self.Bot(1, self.respuesta("Afirmacion") , self.respuesta("Aprendizaje").format(self.usuario))
    respuesta=self.Cambiar_pronombres(self.mensaje_usuario())
    self.Bot(1, self.respuesta("Comprensiva"))
    self.Bot(0, "¿Algún comentario final para agregar a la sesión de hoy?")
    respuesta=self.Cambiar_pronombres(self.mensaje_usuario())
    if respuesta.title() in self.claves["Afirmacion"]:
      self.Bot(1, self.respuesta("Comprensiva"), ", Te leo...")
      self.Cambiar_pronombres(self.mensaje_usuario())
    self.tiempo_aprend.append(str(datetime.now())[:-7])
    
  ##############################################################################
  def Despedida(self, corta=False):
    self.tiempo_sesion.append(str(datetime.now())[:-7])
    if corta:
      self.Bot(0, "Por mi parte es todo,", self.respuesta("Despedida"), self.usuario)
      self.marco("termino")
    else:
      self.Bot(1, self.respuesta("Agradecimiento"), self.usuario, ", espero que la sesión")
      self.Bot(0, "te haya sido de utilidad. Por mi parte es todo")
      self.Bot(0, self.respuesta("Despedida"))
      self.Resumen_final()
      self.marco("termino")
    input("Presiona Enter para terminar la applicación.")
    sys.exit(0)
  
  ##############################################################################
  def No_avanza(self):
    self.Bot(1, "Disculpa, esta conversación no avanza, será mejor que intentemos en otra ocasión")
    self.Despedida(1)
  
  ##############################################################################
  def Negativa(self, respuesta):
    if respuesta.title() in self.claves["Negacion"]:
      self.Bot(1, self.respuesta("Comprensiva"), ", No te preocupes, sigamos avanzando")
      return True
    else:
      return False

  ##############################################################################
  def Cambiar_pronombres(self, texto):
    pron_usuario=["yo", "mi", "mio", "mis", "tu", "tuyo", "ti", "tus"]
    cambio=["tu", "tu", "tuyo", "tus", "yo", "mio", "mi", "mis"]
    lista=texto.split(" ")
    texto_cambio=[]
    for palabra in lista:
      for n, pron in enumerate(pron_usuario):
        if palabra.lower() == pron:
          palabra = cambio[n]
          break
      texto_cambio.append(palabra)
    texto_cambio[0]=texto_cambio[0].title()
    return " ".join(texto_cambio)

  ##############################################################################
  def Resumen_final(self):
    with open("Conversation_X_" + str(datetime.now())[:10].replace("-","_") + ".txt", "w+") as file:
      file.write("ChatBot name: {} \n\n".format(self.name))
      file.write("User name: {} \n\n".format(self.usuario))
      file.write("Chat tópico: {} \n".format(self.tema))
      for n in range(len(self.objetivos)):
        file.write("Chat objectivos: \t * {} \n".format(self.objetivos[n]))

      file.write("\n")
      file.write("\t\tTiempos GROW\n\n")
      tiempos=[self.tiempo_sesion, self.tiempo_tema_obj, self.tiempo_import, 
             self.tiempo_indicador, self.tiempo_explorar, self.tiempo_verif,
             self.tiempo_aprend]
      i=0
      for tiempo in tiempos:
        file.write(self.titulo_grow[i] + " : " + tiempo[0] + " hasta " + tiempo[1] + "\n")
        i+=1
      file.write("\n\n")
      file.write(self.conversacion)